### ISSUE TITLE
breadcrumbs are broken

### ISSUE THREAD

**Issue by mojoaxel** [mojoaxel/d3-sunburst#10]
![image](https://user-images.githubusercontent.com/600565/95687052-91781a00-0c01-11eb-9118-25db29695a6d.png)

This was introduced by #7

**Comment by mojoaxel** [comment]
@puripant Maybe you can have a look at this!?

**Comment by puripant** [comment]
@mojoaxel I will look into it. Do I understand correctly that one layer is missing from the breadcrumb?

**Comment by mojoaxel** [comment]
> I will look into it. Do I understand correctly that one layer is missing from the breadcrumb?

yes. It also "feels" buggy. You could checkout e.g. the [v4.4.2](https://github.com/mojoaxel/d3-sunburst/releases/tag/v4.4.2) tag and run the old version to see how it should behave. Sorry that I missed this in my review...

**Comment by mojoaxel** [comment]
fixed by @puripant with #12
